### ISSUE TITLE
Client crashes after inputting custom Hex Color 

### ISSUE THREAD

**Issue by chrismitchell027** [dantaeusb-mc/Zetter#121]
Below I have attached the list of mods that I am playing with. I am unsure if there is a mod that I am playing with that is known to cause issues, or if this is something new that has not been addressed. For context, I am playing on a multiplayer server on 1.19.4. The server does not crash when this issue comes up, only my own client. I am also running optifine with shaders, if that makes a difference.

 https://www.curseforge.com/minecraft/mc-mods/guard-villagers - Guard Villagers (by almightytallestred) 
 https://www.curseforge.com/minecraft/mc-mods/enchantment-descriptions - Enchantment Descriptions (by DarkhaxDev) 
 https://www.curseforge.com/minecraft/mc-mods/zetter - Zetter — Painting Mod (by dantaeusb) 
 https://www.curseforge.com/minecraft/mc-mods/yungs-better-witch-huts - YUNG's Better Witch Huts (Forge) (by YUNGNICKYOUNG) 
 https://www.curseforge.com/minecraft/mc-mods/travelers-titles - Traveler's Titles (Forge) (by YUNGNICKYOUNG) 
 https://www.curseforge.com/minecraft/mc-mods/yungs-extras - YUNG's Extras (Forge) (by YUNGNICKYOUNG) 
 https://www.curseforge.com/minecraft/mc-mods/yungs-api - YUNG's API (Forge) (by YUNGNICKYOUNG) 
 https://www.curseforge.com/minecraft/mc-mods/bookshelf - Bookshelf (by DarkhaxDev) 
 https://www.curseforge.com/minecraft/mc-mods/jei - Just Enough Items (JEI) (by mezz) 
 https://www.curseforge.com/minecraft/mc-mods/not-enough-animations - Not Enough Animations (by tr7zw) 
 https://www.curseforge.com/minecraft/mc-mods/torchmaster - Torchmaster (by xalcon) 
 https://www.curseforge.com/minecraft/mc-mods/better-ping-display - Better Ping Display (by Quintinity) 
 https://www.curseforge.com/minecraft/mc-mods/yungs-better-mineshafts-forge - YUNG's Better Mineshafts (Forge) (by YUNGNICKYOUNG) 
 https://www.curseforge.com/minecraft/mc-mods/better-third-person - Better Third Person (by Socolio) 
 https://www.curseforge.com/minecraft/mc-mods/golden-hopper - Golden Hopper (by MrCrayfish) 
 https://www.curseforge.com/minecraft/mc-mods/mo-enchantments - Mo' Enchantments (by geosava) 
 https://www.curseforge.com/minecraft/mc-mods/xaeros-minimap - Xaero's Minimap (by xaero96) 
 https://www.curseforge.com/minecraft/mc-mods/backpacked - Backpacked (by MrCrayfish) 
 https://www.curseforge.com/minecraft/mc-mods/the-ghast-cow - The Ghast Cow (by Mrbysco) 
 https://www.curseforge.com/minecraft/mc-mods/balm - Balm (Forge Edition) (by BlayTheNinth) 
 https://www.curseforge.com/minecraft/mc-mods/bountiful - Bountiful (Forge) (by Ejektaflex) 
 https://www.curseforge.com/minecraft/mc-mods/prism-lib - Prism [Forge] (by Grend_G) 
 https://www.curseforge.com/minecraft/mc-mods/bitz-mod - Bitz - Enderite Tools &amp; Armor! (by dejeh0) 
 https://www.curseforge.com/minecraft/mc-mods/natures-compass - Nature's Compass (by Chaosyr) 
 https://www.curseforge.com/minecraft/mc-mods/durability-notifier - Durability Notifier (by Mrbysco) 
 https://www.curseforge.com/minecraft/mc-mods/double-doors - Double Doors (by Serilum) 
 https://www.curseforge.com/minecraft/mc-mods/yungs-better-desert-temples - YUNG's Better Desert Temples (Forge) (by YUNGNICKYOUNG) 
 https://www.curseforge.com/minecraft/mc-mods/jumpy-boats - Jumpy Boats (by LobsterJonn) 
 https://www.curseforge.com/minecraft/mc-mods/collective - Collective (by Serilum) 
 https://www.curseforge.com/minecraft/mc-mods/inventory-sorter - Inventory Sorter (by cpw) 
 https://www.curseforge.com/minecraft/mc-mods/comforts - Comforts (Fabric/Forge/Quilt) (by TheIllusiveC4) 
 https://www.curseforge.com/minecraft/mc-mods/yungs-bridges - YUNG's Bridges (Forge) (by YUNGNICKYOUNG) 
 https://www.curseforge.com/minecraft/mc-mods/iceberg - Iceberg [Forge] (by Grend_G) 
 https://www.curseforge.com/minecraft/mc-mods/immersive-aircraft - Immersive Aircraft [Fabric/Forge] (by Conczin) 
 https://www.curseforge.com/minecraft/mc-mods/corpse - Corpse (by henkelmax) 
 https://www.curseforge.com/minecraft/mc-mods/kotlin-for-forge - Kotlin for Forge (by thedarkcolour) 
 https://www.curseforge.com/minecraft/mc-mods/texels-paintings - Texels Paintings (by builtwithtexels) 
 https://www.curseforge.com/minecraft/mc-mods/yungs-better-strongholds - YUNG's Better Strongholds (Forge) (by YUNGNICKYOUNG) 
 https://www.curseforge.com/minecraft/mc-mods/legendary-tooltips - Legendary Tooltips [Forge] (by Grend_G) 
 https://www.curseforge.com/minecraft/mc-mods/explorers-compass - Explorer's Compass (by Chaosyr) 
 https://www.curseforge.com/minecraft/mc-mods/shulker-tooltip - Shulker Tooltip (by ZephaniahNoah) 
 https://www.curseforge.com/minecraft/mc-mods/kambrik - Kambrik (by Ejektaflex) 
 https://www.curseforge.com/minecraft/mc-mods/appleskin - AppleSkin (by squeek502) 
 https://www.curseforge.com/minecraft/mc-mods/goblin-traders - Goblin Traders (by MrCrayfish) 
 https://www.curseforge.com/minecraft/mc-mods/yungs-better-dungeons - YUNG's Better Dungeons (Forge) (by YUNGNICKYOUNG) 
 https://www.curseforge.com/minecraft/mc-mods/waystones - Waystones (by BlayTheNinth) 
 https://www.curseforge.com/minecraft/mc-mods/yungs-better-ocean-monuments - YUNG's Better Ocean Monuments (Forge) (by YUNGNICKYOUNG) 
 https://www.curseforge.com/minecraft/mc-mods/horse-statistics - Horse Statistics (by nero_surfing) 
 https://www.curseforge.com/minecraft/mc-mods/everythingcopper - Everything is Copper (by LobsterJonn) 
 https://www.curseforge.com/minecraft/mc-mods/mo-villager - Mo' Villager (Redstone + Nether Traders) (by BelgieYT) 
 https://www.curseforge.com/minecraft/mc-mods/immersive-armors - Immersive Armors [Fabric/Forge] (by Conczin) 
 https://www.curseforge.com/minecraft/mc-mods/yungs-better-nether-fortresses - YUNG's Better Nether Fortresses (Forge) (by YUNGNICKYOUNG) 

**Edit: here is the comment from the crash, let me know if any other information would help. Thanks for any help, this mod is great!

"The game crashed whilst mouseclicked event handler
Error: java.lang.StackOverflowError: mouseClicked event handler"

**Comment by DarthShader** [comment]
Also having this issue. Call stack repeats these function calls

```
at me.dantaeusb.zetter.client.gui.easel.ColorCodeWidget.updateColorValue(ColorCodeWidget.java:92) ~[zetter-0.21.1-1.19.4-rc.jar%23313!/:0.21.1-1.19.4-rc] {re:classloading}
at me.dantaeusb.zetter.client.gui.easel.tabs.ColorTab.update(ColorTab.java:40) ~[zetter-0.21.1-1.19.4-rc.jar%23313!/:0.21.1-1.19.4-rc] {re:classloading}
at me.dantaeusb.zetter.client.gui.EaselScreen.updateCurrentColor(EaselScreen.java:175) ~[zetter-0.21.1-1.19.4-rc.jar%23313!/:0.21.1-1.19.4-rc] {re:classloading}
at me.dantaeusb.zetter.menu.EaselMenu.notifyColorUpdateListeners(EaselMenu.java:335) ~[zetter-0.21.1-1.19.4-rc.jar%23313!/:0.21.1-1.19.4-rc] {re:classloading}
at me.dantaeusb.zetter.menu.EaselMenu.setPaletteColor(EaselMenu.java:458) ~[zetter-0.21.1-1.19.4-rc.jar%23313!/:0.21.1-1.19.4-rc] {re:classloading}
at me.dantaeusb.zetter.menu.EaselMenu.setPaletteColor(EaselMenu.java:446) ~[zetter-0.21.1-1.19.4-rc.jar%23313!/:0.21.1-1.19.4-rc] {re:classloading}
at me.dantaeusb.zetter.client.gui.easel.ColorCodeWidget.applyColor(ColorCodeWidget.java:119) ~[zetter-0.21.1-1.19.4-rc.jar%23313!/:0.21.1-1.19.4-rc] {re:classloading}
at net.minecraft.client.gui.components.EditBox.m_94174_(EditBox.java:149) ~[client-1.19.4-20230314.122934-srg.jar%23314!/:?] {re:mixin,re:classloading,pl:mixin:A}
at net.minecraft.client.gui.components.EditBox.m_94192_(EditBox.java:255) ~[client-1.19.4-20230314.122934-srg.jar%23314!/:?] {re:mixin,re:classloading,pl:mixin:A}
at net.minecraft.client.gui.components.EditBox.m_94201_(EditBox.java:267) ~[client-1.19.4-20230314.122934-srg.jar%23314!/:?] {re:mixin,re:classloading,pl:mixin:A}
at net.minecraft.client.gui.components.EditBox.m_94144_(EditBox.java:103) ~[client-1.19.4-20230314.122934-srg.jar%23314!/:?] {re:mixin,re:classloading,pl:mixin:A}
```

**Comment by DarthShader** [comment]
It appears this issue was fixed in the MC 1.20 targeted release but the fix was never backported to older versions.

**Comment by dantaeusb** [comment]
Just made a new version, with a very quick check. Uploaded only to Modrinth for now, later will do for Forge if everything is alright:
Zetter Gallery: https://modrinth.com/mod/zetter-gallery-share-paintings/version/dxSqAkzO
Zetter: https://modrinth.com/mod/zetter-painting-mod/version/vfGCxswo

**Comment by dantaeusb** [comment]
I will keep this issue opened for a week for any problems. Then will close and upload to CF.
