### ISSUE TITLE
Бесконечные картины, если вешать их из Offhand.

### ISSUE THREAD

**Issue by GitJhopa** [dantaeusb-mc/Zetter#129]
Бесконечные картины, если вешать их из Offhand. Рисуем картину - подписываем, берем во вторую руку - вешаем на стену - картины бесконечные. Forge 1.19.2

**Comment by GitJhopa** [comment]
Спасибо братишка, что пофиксил, но где 1.19.2 вопрос

**Comment by dantaeusb** [comment]
А чё там? Фиксы я потом буду делать, сейчас у меня пару новых фич в работе.  
Если ты про #127 то там как будто не критично, я хз как у кого-то получилось написать целых 47 символов в имени картины; но по идее на работу мода в общем это не должно влиять.

**Comment by dantaeusb** [comment]
Fixed in 1.19.2 & 1.20.1
