### ISSUE TITLE
Crash when placing easel item on a server.

### ISSUE THREAD

**Issue by mekrod** [dantaeusb-mc/Zetter#17]
It gives the following error: Internal Exception: io.netty.handler.codec.EncoderException: java.lang.NullPointerException: Cannot Invoke "String.getBytes(java.nio.charset.Charset)" because "p_130073_" is null.

On server Log: Error encoding packet
java.lang.NullPointerException: Cannot invoke "String.getBytes(java.nio.charset.Charset)" because "p_130073_" is null

**Comment by dantaeusb** [comment]
Thank you for report, version 1.12.1 for 1.18.1 with fix is available on CurseForge, and fix for 1.17.1 will be available a bit later.
