### ISSUE TITLE
Crash on placing artist table

### ISSUE THREAD

**Issue by geheimtur** [dantaeusb-mc/Zetter#18]
I'm getting this error after placing the table in the world:

Description: Exception ticking world

java.lang.NoSuchMethodError: 'net.minecraft.nbt.CompoundTag com.dantaeusb.zetter.block.entity.ArtistTableBlockEntity.save(net.minecraft.nbt.CompoundTag)'

Happy to share the entire crashlog if it would be helpful!

**Comment by dantaeusb** [comment]
HI! Yes, please, can you share your crashlog here? I'm trying to reproduce the issue on different versions, but not able to get this error.

Seems like it might happen here https://github.com/dantaeusb-mc/Zetter/blob/f3c42c6279d711dc86ef72132a56a4ea4f4eee74/src/main/java/me/dantaeusb/zetter/deprecated/block/entity/EaselBlockEntity.java#L81, but there's nothing to crash, so I need more details definitely.

**Comment by geheimtur** [comment]
[crash-2022-02-13_22.35.09-server.txt](https://github.com/dantaeusb-mc/Zetter/files/8064905/crash-2022-02-13_22.35.09-server.txt)

**Comment by geheimtur** [comment]
Absolutely! Glad to help :) Appreciate the shoutout in the patch notes!
