### ISSUE TITLE
Suggestion: Simplify Artist Table Recipe

### ISSUE THREAD

**Issue by BreadBxsket** [dantaeusb-mc/Zetter#22]
Reason: Consistency with Vanilla recipes for similar 1.14 workstations (Loom, Fletching Table, Cartography Cable, Smithing Table)

Possibilities:
![image](https://user-images.githubusercontent.com/30668741/155993222-86d19d23-4681-485c-ac52-47497a8b7044.png)

All options maintain the use of _Paints_ and _Paper_, while the second option maintains the _slabs_, and the third option maintains having _slabs on top_. All options make the recipe smaller and more in-line with similar 1.14 workstations.

**Comment by dantaeusb** [comment]
Implemented in 0.19
