### ISSUE TITLE
Suggestion: Renamed canvas to "blank canvas" and "painted canvas" depending on if it is blank

### ISSUE THREAD

**Issue by TheDeviantCrafter** [dantaeusb-mc/Zetter#25]
Right now there is no clear feedback to show when a canvas contains painting data. I suggest renaming the item to "blank canvas" when it's empty, and "painted canvas" when it has been painted.

**Comment by dantaeusb** [comment]
Makes sense. Also, in dev branch I was working on showing actual painting on canvas instead of canvas icon, but had some troubles so far. I'll keep in mind to change the item name also when I'll be working on that feature.

**Comment by dantaeusb** [comment]
Done in 0.16.0. Though, due to way canvas initialization works, any canvas that was used on easel - even if no painting made, will be painted canvas. This might change later.
