### ISSUE TITLE
Suggestion: Allow empty frames to be placed in the world

### ISSUE THREAD

**Issue by TheDeviantCrafter** [dantaeusb-mc/Zetter#28]
Because frames are very similar to vanilla item frames, it may be more intuitive to use the same mechanics. I suggest allowing empty frames to be placed in the world. Paintings could then be inserted by right clicking an empty frame in the world instead of using a crafting table.

Framed paintings already have a leather texture on the back side. That could be copied to the front.

**Comment by dantaeusb** [comment]
The thing is that frames without paintings cannot know which size should they be. I can use the same way that vanilla paintings work -- to keep the most space possible, but not sure if that's needed. 

What do you think is a use-case for such frames? Or the ides is just to keep things consistent with vanilla?

**Comment by TheDeviantCrafter** [comment]
They could function like prettier vanilla item frames.

**Comment by dantaeusb** [comment]
Revisiting this, I still think it's out of the mod's scope, and I want to keep this particular mod in very "strict bounds" of what it is. Something like Quark could have different wood type frames.
